# Generated by Django 6.0.5 on 2026-05-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(max_length=200)),
                ('correo_responsable', models.EmailField(blank=True, max_length=254)),
                ('nombre_evento', models.CharField(max_length=200)),
                ('num_asistentes', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente')], default='CONFIRMADO', max_length=20)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('AULA', 'Aula (Sillas y mesas)'), ('AUDITORIO', 'Auditorio (Sillas)'), ('HERRADURA', 'Herradura (Configuración en U)')], max_length=20)),
                ('capacidad', models.PositiveIntegerField(default=40)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='ReglaRecurrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], max_length=10)),
                ('fecha_fin_serie', models.DateField()),
                ('evento_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrencia', to='gestion.evento')),
            ],
            options={
                'verbose_name': 'Regla de Recurrencia',
                'verbose_name_plural': 'Reglas de Recurrencia',
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DAÑO', 'Daño en equipo'), ('FALLA', 'Falla técnica'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='gestion.evento')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='gestion.sala')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='salas',
            field=models.ManyToManyField(related_name='eventos', to='gestion.sala'),
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACOMODO', 'Acomodo de mobiliario'), ('SONIDO', 'Equipo de sonido'), ('CAFETERIA', 'Cafetería'), ('VIDEOCONF', 'Videoconferencia')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='gestion.evento')),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
                'verbose_name_plural': 'Servicios Adicionales',
            },
        ),
    ]
