# Generated by Django 6.0.5 on 2026-06-22 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acomodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Acomodo',
                'verbose_name_plural': 'Acomodos',
            },
        ),
        migrations.RemoveField(
            model_name='evento',
            name='salas',
        ),
        migrations.AlterField(
            model_name='reglarecurrencia',
            name='evento_base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regla_recurrencia', to='gestion.evento'),
        ),
        migrations.CreateModel(
            name='EventoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acomodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.acomodo')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.evento')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sala')),
            ],
            options={
                'verbose_name': 'Sala Asignada',
                'verbose_name_plural': 'Salas Asignadas',
                'unique_together': {('evento', 'sala')},
            },
        ),
    ]
