# Generated by Django 6.0.5 on 2026-06-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_acomodo_remove_evento_salas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='salas',
            field=models.ManyToManyField(related_name='eventos', through='gestion.EventoSala', to='gestion.sala'),
        ),
    ]
