# Generated by Django 6.0.5 on 2026-06-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_evento_salas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='tipo',
        ),
    ]
